#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x xss-lock > /dev/null || xss-lock -- i3lock -n &
pgrep -x polybar > /dev/null || polybar &
pgrep -x picom > /dev/null || picom &
pgrep -x feh > /dev/null || feh --no-fehbg --bg-fill --randomize ~/Pictures/wallpaper/* &
pgrep -x fcitx > /dev/null || fcitx -d

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width          2
bspc config window_gap            12
bspc config split_ratio           0.56
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a feh    state=floating
bspc rule -a mpv    state=floating
bspc rule -a okular state=floating

